### ISSUE TITLE
Fatal error: Can’t use function return value in write context /local/msaccount/classes/client.php on line 62

### ISSUE THREAD

**Issue by jsiko11** [Microsoft/moodle-local_msaccount#1]
Hi,
I try to install this plugin on Moodle 2.8 but I get the following error while installing : 

Fatal error: Can’t use function return value in write context <Moodle_URL>/local/msaccount/classes/client.php on line 62

Line 62 :

        if (empty(get_config('local_msaccount', 'clientid')) || empty(get_config('local_msaccount','clientsecret'))) {
               return false;
        }

Internally empty uses isset function for check if the giving variable exists but there is not variable. So solution is initialize variables before if statement.

Solution for Line 62 :

        $clientID = get_config('local_msaccount', 'clientid');
        $clientSecret = get_config('local_msaccount', 'clientsecret');
        if (empty($clientID) || empty($clientSecret)) {
            return false;
        }

**Comment by jamesmcq** [comment]
That's for the report - can confirm the issue and will get it fixed as soon as possible.

**Comment by jamesmcq** [comment]
Thanks for the report and patch! 

The fix for this issue is in our dev repository at https://github.com/Microsoft/o365-moodle. The patch is in branches [wip-MSFTMPP-328-m30](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-328-m30), [wip-MSFTMPP-328-m29](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-328-m29), [wip-MSFTMPP-328-m28](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-328-m28), [wip-MSFTMPP-328-m27](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-328-m27). 

This will be included in our next release.
